apiVersion: v1
kind: DeploymentConfig
metadata:
  name: jenkins-openpaas
  namespace: cicd-asia
  selfLink: /oapi/v1/namespaces/cicd-asia/deploymentconfigs/jenkins-openpaas
  uid: d5a2e0be-8b9c-11e6-9141-027e726f02e5
  resourceVersion: '7503529'
  creationTimestamp: '2016-10-06T08:13:59Z'
  labels:
    app: jenkins-openpaas
    created-by: template
  annotations:
    openshift.io/deployment.cancelled: '11'
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {  }
  triggers:
    -
      type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: jenkins-openpaas
    deploymentconfig: jenkins-openpaas
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins-openpaas
        deploymentconfig: jenkins-openpaas
    spec:
      volumes:
        -
          name: jenkins-openpaas-data
          persistentVolumeClaim:
            claimName: jenkins-openpaas-data
      containers:
        -
          name: jenkins-openpaas
          image: 'kalote/jenkinsos:1.0.2'
          ports:
            -
              containerPort: 8080
              protocol: TCP
            -
              containerPort: 50000
              protocol: TCP
          env:
            -
              name: http_proxy_host
              value: default-http-proxy.pink.ap-southeast-1.aws.openpaas.axa-cloud.com
            -
              name: http_proxy_port
              value: '8888'
            -
              name: https_proxy_host
              value: default-http-proxy.pink.ap-southeast-1.aws.openpaas.axa-cloud.com
            -
              name: https_proxy_port
              value: '8888'
          resources:
            limits:
              cpu: '2'
              memory: 6Gi
          volumeMounts:
            -
              name: jenkins-openpaas-data
              mountPath: /var/jenkins_home
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {  }
status:
  latestVersion: 11
  details:
    causes:
      -
        type: ConfigChange
